inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'spec/dummy/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  Enabled: false
